#!/usr/bin/env python2.7
"""
Publish AO audit data via git.

EXAMPLES:

To ...

    %(prog)s

"""

#############################################################################
# Copyright (c) 2005-2016 David Boyce.  All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

from __future__ import print_function
from __future__ import unicode_literals

import argparse

# import actions


def main():
    """Entry point for standalone use."""

    parser = argparse.ArgumentParser(
        epilog=__doc__.strip(),
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        '-m', '--members-only', action='store_true',
        help='ignore files which are not project members')
    parser.add_argument(
        'audit', nargs='?',
        help='optional audit file')
    opts = parser.parse_args()

    print('stub for now {0}'.format(opts.audit))

if __name__ == '__main__':
    main()

# vim: ts=8:sw=4:tw=80:et:
